### ISSUE TITLE
Issues to run the code 

### ISSUE THREAD

**Issue by an-na-m** [fk128/ct-slice-detection#2]
Hello, 

Thank you for providing your work and the code here.
I have tried to run the code, but I have encountered multiple issues (missing modules) which I was able to solve. 
I have one syntax error that I am not able to solve myself:

operating system name and version: Mac OS Catalina, version 10.15.6

`(base) USERs-Air:~ User$ cd /Users/User/Downloads/ct-slice-detection-master/

(base) USERs-Air:ct-slice-detection-master User$ python setup.py develop

running develop

running egg_info

writing requirements to ct_slice_detection.egg-info/requires.txt

writing ct_slice_detection.egg-info/PKG-INFO

writing top-level names to ct_slice_detection.egg-info/top_level.txt

writing dependency_links to ct_slice_detection.egg-info/dependency_links.txt

writing entry points to ct_slice_detection.egg-info/entry_points.txt

reading manifest file 'ct_slice_detection.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no files found matching 'README.rst'

warning: no files found matching '*' under directory 'tests'

warning: no previously-included files matching '__pycache__' found under directory '*'

warning: no previously-included files matching '*.py[co]' found under directory '*'

warning: no files found matching '*.jpg' under directory 'docs'

warning: no files found matching '*.png' under directory 'docs'

warning: no files found matching '*.gif' under directory 'docs'

writing manifest file 'ct_slice_detection.egg-info/SOURCES.txt'

running build_ext

Creating /opt/anaconda2/lib/python2.7/site-packages/ct-slice-detection.egg-link (link to .)

ct-slice-detection 0.1.0 is already the active version in easy-install.pth

Installing l3_detect_trainer script to /opt/anaconda2/bin

Installing l3_detect_tester script to /opt/anaconda2/bin

 

Installed /Users/User/Downloads/ct-slice-detection-master

Processing dependencies for ct-slice-detection==0.1.0

Searching for imageio==2.6.0

Best match: imageio 2.6.0

Adding imageio 2.6.0 to easy-install.pth file

Installing imageio_download_bin script to /opt/anaconda2/bin

Installing imageio_remove_bin script to /opt/anaconda2/bin

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for scikit-learn==0.20.3

Best match: scikit-learn 0.20.3

Adding scikit-learn 0.20.3 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for numpy==1.16.6

Best match: numpy 1.16.6

Adding numpy 1.16.6 to easy-install.pth file

Installing f2py2 script to /opt/anaconda2/bin

Installing f2py script to /opt/anaconda2/bin

Installing f2py2.7 script to /opt/anaconda2/bin

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for opencv-contrib-python==4.2.0.32

Best match: opencv-contrib-python 4.2.0.32

Processing opencv_contrib_python-4.2.0.32-py2.7-macosx-10.7-x86_64.egg

opencv-contrib-python 4.2.0.32 is already the active version in easy-install.pth

 

Using /opt/anaconda2/lib/python2.7/site-packages/opencv_contrib_python-4.2.0.32-py2.7-macosx-10.7-x86_64.egg

Searching for pandas==0.24.2

Best match: pandas 0.24.2

Adding pandas 0.24.2 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for Keras==2.2.4

Best match: Keras 2.2.4

Adding Keras 2.2.4 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for scipy==1.2.2

Best match: scipy 1.2.2

Adding scipy 1.2.2 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for futures==3.3.0

Best match: futures 3.3.0

Adding futures 3.3.0 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for enum34==1.1.10

Best match: enum34 1.1.10

Adding enum34 1.1.10 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for Pillow==6.2.0

Best match: Pillow 6.2.0

Adding Pillow 6.2.0 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for python-dateutil==2.8.0

Best match: python-dateutil 2.8.0

Adding python-dateutil 2.8.0 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for pytz==2019.3

Best match: pytz 2019.3

Adding pytz 2019.3 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for h5py==2.9.0

Best match: h5py 2.9.0

Adding h5py 2.9.0 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for Keras-Applications==1.0.8

Best match: Keras-Applications 1.0.8

Adding Keras-Applications 1.0.8 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for PyYAML==5.1.1

Best match: PyYAML 5.1.1

Adding PyYAML 5.1.1 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for Keras-Preprocessing==1.1.2

Best match: Keras-Preprocessing 1.1.2

Adding Keras-Preprocessing 1.1.2 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Searching for six==1.15.0

Best match: six 1.15.0

Adding six 1.15.0 to easy-install.pth file

 

Using /opt/anaconda2/lib/python2.7/site-packages

Finished processing dependencies for ct-slice-detection==0.1.0

(base) USERs-Air:ct-slice-detection-master User$ python /opt/anaconda2/bin/l3_detect_trainer --config configs/slice_detect_1d.cfg

Using TensorFlow backend.

Traceback (most recent call last):

  File "/opt/anaconda2/bin/l3_detect_trainer", line 11, in <module>

    load_entry_point('ct-slice-detection', 'console_scripts', 'l3_detect_trainer')()

  File "/Users/User/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

  File "/Users/User/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point

    return ep.load()

  File "/Users/User/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load

    return self.resolve()

  File "/Users/User/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/Users/User/Downloads/ct-slice-detection-master/ct_slice_detection/trainer.py", line 10, in <module>

    from ct_slice_detection.utils.training_utils import PreviewOutput

  File "/Users/User/Downloads/ct-slice-detection-master/ct_slice_detection/utils/training_utils.py", line 3, in <module>

    from .testing_utils import *

  File "/Users/User/Downloads/ct-slice-detection-master/ct_slice_detection/utils/testing_utils.py", line 12, in <module>

    from .generic_utils import printProgressBar

  File "/Users/User/Downloads/ct-slice-detection-master/ct_slice_detection/utils/generic_utils.py", line 20

    print('\r%s |%s| %s%% %s' % (prefix, bar, percent, suffix), end='\r')

                                                                   ^

SyntaxError: invalid syntax`

**Comment by fk128** [comment]
Use python 3.6 not python 2.7
