### ISSUE TITLE
Packages version compatible with the code

### ISSUE THREAD

**Issue by agdestine** [fk128/ct-slice-detection#3]
Hi,

I am having this issue when trying to run the code on my environment. I am using a Mac OS (Catalina Version 10.15.6) and Python 3.8.6rc1 (v3.8.6rc1:08bd63da6e, Sep  7 2020, 16:14:12). (not under anaconda)

I faced a couple of issues, maybe due to wrong TensorFlow and Kera versions. I manage to solve them using those version:
tensorflow 2.2.0 and keras 2.2...
I couldn't find the right version for those packages on the project documentation.

As of now, below are the error messages I am having: 
-------
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

keras 2.2.0 requires keras-preprocessing==1.0.1, but you'll have keras-preprocessing 1.1.0 which is incompatible.
-------

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow 2.2.0 requires keras-preprocessing>=1.1.0, but you'll have keras-preprocessing 1.0.1 which is incompatible.
-------

Could you please indicate what are the good versions to use for the following packages:
- tensorflow
- keras
- keras-preprocessing

Thanks in advance.

Best regards,

Archange

**Comment by fk128** [comment]
Please see https://github.com/fk128/sarcopenia-ai and use docker
